### PR TITLE
[Updated PR#1854] Added aggregate-sample function to generate random result from query

### PR DESCRIPTION
**Pull request by Giacomo92**
This PR was recreated from #1854 
--

The sample() function is used to generate random result based on the given size. It can be used together with eloquent functions like ```where()`` and such.

Co-Authored-By: @adlanarifzr

### CODE REVIEW

**Comment by divine** [comment]
Do we really need to add this feature?

**Comment by jenssegers** [comment]
While it does look like a neat feature, I also think it's really important to add it to the library. My idea of this library is to make it super easy for Laravel developers to switch between SQL/Mongo database implementations without having to change too much of their code. This sample method feels very Mongo oriented. But then again, there are already quite some Mongo specific features in the library right now.

**Comment by Giacomo92** [comment]
There are some of issues asking for randomness.
https://github.com/jenssegers/laravel-mongodb/issues/107
https://github.com/jenssegers/laravel-mongodb/issues/1493

For now the only way to get random data is to use collection. In Laravel there is a method to called `inRandomOrder`  see [here](https://laravel.com/docs/5.7/queries#ordering-grouping-limit-and-offset) to achieve that without using the collection. In my opinion If this package has to be "super easy for Laravel developers", it is not possible to run a raw query to get random data from the database.

**Comment by divine** [comment]
> There are some of issues asking for randomness.
> #107
> #1493
> 
> For now the only way to get random data is to use collection. In Laravel there is a method to called `inRandomOrder` see [here](https://laravel.com/docs/5.7/queries#ordering-grouping-limit-and-offset) to achieve that without using the collection. In my opinion If this package has to be "super easy for Laravel developers", it is not possible to run a raw query to get random data from the database.

My suggestion would be to add this function in the next version when we refactor a little bit of pipeline, not this maintenance release which is almost fixing everything.

Regarding #107, #1493 we have important issues such not working relations, enchantments could be worked on when everythings works as expected at least.

What do you think about this @Smolevich ?

**Comment by divine** [comment]
After internal discussion we have decided this is not the right time to add this new feature in the current release.

**Comment by mean-cj** [comment]
I thank this feature we are need. 
better than sample() to inRandomOrder()  can support both SQL/Mongo it better.

**Pull request closed without merging**
