### PR TITLE
Add Hybrid `has` and `whereHas` functionality

### LINKED ISSUE #1035: Querying Sql Model relationship existence with mongo model
Hi,

Getting this error when am querying  sql model with mongo model relation existence

```php
Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'exists ?) order by `modified_at` desc' at line 1 in /var/www/test/vendor/illuminate/database/Connection.php:333
Stack trace:
#0 /var/www/test/vendor/illuminate/database/Connection.php(333): PDO-&gt;prepare('select * from `...')
#1 /var/www/test/vendor/illuminate/database/Connection.php(722): Illuminate\Database\Connection-&gt;Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select * from `...', Array)
#2 /var/www/test/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection-&gt;runQueryCallback('select * from `...', Array, Object(Closure))
#3 /var/www/test/vendor/illuminate/database/Connection.php(349): Illuminate\Database\Connection-&gt;run('select * from `...', Array, Object(Closure))
#4 /var/www/test/vendor/illuminate/database/Query/Builder.php(161 in
/var/www/test/vendor/illuminate/database/Connection.php on line 729 
```

**Sql Model** 
```php
namespace App\Models\Sql;

use Illuminate\Database\Eloquent\Model;
use Jenssegers\Mongodb\Eloquent\HybridRelations;

class History extends Model
{
	use HybridRelations;
	
	/** @var string Connection Name */
	protected $connection = 'default';
	
	/**
	 * History with Campagin Details
	 * @return \Jenssegers\Mongodb\Relations\HasOne
	 */
	public function campaign()
	{
		return $this->hasOne('\App\Models\Mongo\Campaign', 'campaign.campaign_id', 'campaign_id');
	}
}
```

This way am checking  relation existence. If i remove `has` it works fine but using  `has` throws the `PDOException` error

```php
$history = History::where([
	// some condition
])
->has('campaign')
->with('campaign')
->orderBy('modified_at', 'desc')
->get();
```

and here is the sql query formed

```sql
select * from `user_campaign_history` where ( <some_conditions> = ?) and exists (select * from `campaigns` where `campaign`.`campaign_id` exists ?) order by `modified_at` desc
```

### PR DESCRIPTION
**Pull request by Tucker-Eric**
This adds the support for `has` and `whereHas` for hybrid relations between mongodb models and mysql models.

This should close #1035, #803, #730, #342, #1225, and #1159

### CODE REVIEW

**Comment by martingg88** [comment]
any update to commit into master version?

**Comment by vesper8** [comment]
@martingg88 I have been using this branch for almost 2 months now and haven't had any problems at all

@jenssegers I really wish you would merge this one in or at least take a look at it.. a lot of people have been requesting this addition for a very long time now

**Comment by Tucker-Eric** [comment]
Tests are passing now but StyleCI hates me

**Comment by jenssegers** [comment]
Sorry for the delay!

**Comment by alquesadilla** [comment]
Call to undefined method Jenssegers\Mongodb\Query\Builder::getRelationWithoutConstraints()  when use dev-master

**Pull request merged**
