### PR TITLE
[Fix] Unable to delete nested embedded models

### PR DESCRIPTION
**Pull request by milanspv**
The PR fixes deletion of embedded nested objects.
The current implementation uses dot notation which in combination with `$set` update operator does not actually remove objects.

@jenssegers ^

### CODE REVIEW

**Comment by milanspv** [comment]
@jenssegers any updates on this?

**Comment by milanspv** [comment]
@jenssegers Could you please review the PR and provide any kind of feedback? The review should be prioritized since it contains a fix for the core functionality that is not working properly in the current implementation.

**Comment by jenssegers** [comment]
Merged, but GitHub did something weird :)

https://github.com/jenssegers/laravel-mongodb/commit/7445ea6cc0a139f40ac9cfe1b15952c961e58793

**Comment by milanspv** [comment]
@jenssegers what version of the package will this be available on? Ref: https://github.com/jenssegers/laravel-mongodb/pull/1423#issuecomment-368486582

**Comment by jenssegers** [comment]
@milanspv v3.4.1

**Comment by milanspv** [comment]
@jenssegers v3.4.1 requires Laravel 5.6. Any chance to make this available to those of us who work with Laravel 5.5 LTS (v3.3.x release)?

**Pull request closed without merging**
