### PR TITLE
feat: add mongodb passport support

### PR DESCRIPTION
**Pull request by StevePorter92**
Similar to the passport service provider in https://github.com/moloquent/moloquent.

### CODE REVIEW

**Comment by Christophvh** [comment]
I manually did your implementation and it worked fine, not sure why the travis test is failing.

**Comment by DMNSteve** [comment]
Looks like the Travis test is failing because the mongo php extension is already installed.

**Comment by DMNSteve** [comment]
Hey @jenssegers. Would you mind reviewing this when you have a change? Thanks!

**Comment by LeonAlvarez** [comment]
@DMNSteve  Im having issue with Password Grant Tokens, the tokens user_id is always the first use on my DB, no matter wich credentials I use

**Comment by igorhaf** [comment]
I did this solution while this changes is not approved

https://gist.github.com/igorhaf/8450f6868b15a4ae195fc60e6a2a8118

**Comment by LeonAlvarez** [comment]
Maybe could be better to  split in different a package, so that we can choose when to add it or not. Could do same for other official L ecosystem package that need MongoDB tuning, like Cashier.
So we could have MongoDB adaptors package unders laravel-mongodb ecosystem.
@DMNSteve @jenssegers

**Comment by StevePorter92** [comment]
@LeonAlvarez good idea. I've moved this code to its own package. This way we can leave it up to the discretion of users as to whether they want to implement Laravel passport support

https://github.com/StevePorter92/laravel-mongodb-passport

Closing this issue

**Comment by ivivivn** [comment]
Thanks, this help me a lot. 

But acutally, I am using Lumen which do not support AliasLoader so instead of using AliasLoader I have to use `class_alias` like this

`class_alias(<Rewrited Class>, 'Laravel\Passport\AuthCode');`

In case of someone face it like me.

**Comment by StevePorter92** [comment]
Thanks @ivivivn, I've added an issue to fix Lumen support

**Comment by abd-mhainy** [comment]
thanks @StevePorter92 that's worked for me also i have been facing the same issue

**Comment by sedrak1987** [comment]
use my package for mongodb(based to Laravel passport, so you can use Passport doc)
https://packagist.org/packages/sedrak/laravel-mongodb-passport
remove larvel passport from composer and install this.

**Comment by sedrak1987** [comment]
use my package for mongodb(based to Laravel passport, so you can use Passport doc)
https://packagist.org/packages/sedrak/laravel-mongodb-passport
remove larvel passport from composer and install this.

**Pull request closed without merging**
