### PR TITLE
items instance Eloquent Collection in paginate

### PR DESCRIPTION
**Pull request by SamsamBabadi**
in embeds many relation in paginate method items must be instance of Eloquent Collection same as get method

### CODE REVIEW

**Comment by hamid-kholghi** [comment]
it need that

**Comment by SamsamBabadi** [comment]
is there anybody?

**Comment by SamsamBabadi** [comment]
@jenssegers do you want to check this pull request?

**Comment by amgir** [comment]
Is there a reason this hasn't been merged yet?

**Comment by amin-mirmahmoudi** [comment]
@SamsamBabadi  tanks :) .

**Comment by bastianjoel** [comment]
This is needed to get Eloquent resources to work properly.
https://laravel.com/docs/5.8/eloquent-resources

**Comment by divine** [comment]
Hello!

Could you please update with the base branch or we can take a look?

Thank you for your contribution!

**Comment by SamsamBabadi** [comment]
Hi @divine,

Updated.

**Comment by Giacomo92** [comment]
Can you also add some tests, please? @SamsamBabadi

**Comment by Giacomo92** [comment]
You can close this @Smolevich . It is solved with #1959

**Pull request closed without merging**
