### PR TITLE
Handle case of array of ObjectIDs correctly

### PR DESCRIPTION
**Pull request by henry701**
In case an array of ObjectId-formatted Strings enter this method, this converts them to ObjectIds so that the query succeeds. Happens when calling 'get' method for one-to-many relations.

### CODE REVIEW

**Comment by Smolevich** [comment]
@henry701, tests failed in your PR, check please. Seems like breaking changes

**Comment by henry701** [comment]
Will check when i can. Sorry for taking long, I didn't check that the broken tests weren't flagged before but should have.

**Comment by Smolevich** [comment]
Ok. You can join to slack channel. Link [here](https://github.com/jenssegers/laravel-mongodb/issues/1791)

**Comment by henry701** [comment]
So... For information, I also ran the tests on the master branch using the clover docker-compose setup (`docker-compose run --rm tests ./vendor/bin/phpunit --coverage-clover ./clover.xml`) and the same tests that are failing on the current master branch are failing for my patch branch (class Scope not being found)...

**Comment by divine** [comment]
> So... For information, I also ran the tests on the master branch using the clover docker-compose setup (`docker-compose run --rm tests ./vendor/bin/phpunit --coverage-clover ./clover.xml`) and the same tests that are failing on the current master branch are failing for my patch branch (class Scope not being found)...

Hello,

We will need to wait PR https://github.com/jenssegers/laravel-mongodb/pull/1923 which will fix failing ci.

Thank you for your contribution!

**Comment by Smolevich** [comment]
@henry701 merge actual master

**Comment by Smolevich** [comment]
@henry701 Add test case to https://github.com/jenssegers/laravel-mongodb/blob/master/tests/RelationsTest.php so we are sure it works correctly

**Comment by henry701** [comment]
So I was trying to reproduce the original problem using unit tests today but didn't manage to, yet. All the use cases i created worked with both versions of the code.

I will probably use a manual test on the old version of my backend which was having this issue and debug the sent query to MongoDB again, but it will take a while. The problem involves

Well, I guess that's a lesson learned the hard way: Always reproduce in an isolated manner before fixing something.

When I have new updates regarding this issue, I will comment here again and update the branch.

**Comment by divine** [comment]
Hello,

Please let us know when you've checked your issue and added tests of course.

Closing for now.

Thanks.

**Pull request closed without merging**
