### PR TITLE
add pipeline method for raw mongodb queries.

### PR DESCRIPTION
**Pull request by erblinbobaj**
Add pipeline method for raw mongodb queries.

### CODE REVIEW

**Comment by rennokki** [comment]
This repo seems like it gets slow updates. Would you mind switching for https://github.com/rennokki/laravel-mongodb and submitting this PR down there?

**Comment by jenssegers** [comment]
Would it be possible to add a test and possibly an example in the documentation?

**Comment by rennokki** [comment]
I think it's the same like the `whereRaw` method.

**Comment by divine** [comment]
Hello,

Sorry for late reply, this will be in upcoming version 4.

Thank you.

**Pull request closed without merging**
