### PR TITLE
Add Attributes to the Pivot Embed

### PR DESCRIPTION
**Pull request by AAllport**
Adds Attributes to the Pivot Embed,

Currently got the attribute saving, and retrieval.
Just having a few issues when it comes to eager loading

Help would be appreciated

Supersedes: #1794
Fixes: #1618

### CODE REVIEW

**Comment by AAllport** [comment]
Current issue is for `RelationsTest.testBelongsToManyCustom()`
Loading the relationship with custom param's causes breakage, and I could do with some test's to legacy

- [ ] [Fix] `RelationsTest.testBelongsToManyCustom()`
- [ ] [Test] Legacy relations

**Comment by AAllport** [comment]
Currently seeing this error on Cadacy

**Comment by AAllport** [comment]
Please Review: @jenssegers

**Comment by AAllport** [comment]
Please review: @jenssegers

**Comment by Smolevich** [comment]
@AAllport, please resolve conflicts

**Comment by divine** [comment]
Closing in favor of https://github.com/jenssegers/laravel-mongodb/pull/1952, this hasn't been even replied or taken care at all.

**Pull request closed without merging**
