### PR TITLE
Laravel 5.6 support

### PR DESCRIPTION
**Pull request by RemiCollin**
- Update dependencies
- Fix some method signatures compatible with laravel 5.6
- Remove PHP7.0 job from travis

### CODE REVIEW

**Comment by RemiCollin** [comment]
Update : have a near working Travis script for 7.1/7.2, but mongodb connection is still failing in the tests :

```
MongoDB\Driver\Exception\ConnectionTimeoutException: No suitable servers found (`serverSelectionTryOnce` set): [Failed to resolve 'mongodb']
```

if anyone has a clue ?

**Comment by pierrocknroll** [comment]
Please merge :)

**Comment by kikky7** [comment]
When will this support be available?

**Comment by solofeed** [comment]
Still waiting for merge)
Thank you for PR)

**Comment by bsormagec** [comment]
Thanks for support @RemiCollin

**Comment by pierrocknroll** [comment]
Go go go !

**Comment by avirdz** [comment]
Waiting for this

**Comment by Oliver-Meyer** [comment]
Also waiting - please merge :o)

**Comment by lalawunderland** [comment]
Would be nice if someone could merge it ^.^°

**Comment by thilanga** [comment]
@jenssegers can we get this PR merge to master?

**Comment by IgnitedCoder** [comment]
@jenssegers  Any chance of an update on this PR. We just moved to 5.6 and on a tight deadline. Sorry for the nudge.

**Comment by solofeed** [comment]
@IgnitedCoder why did you hurry up to update?
What so important in 5.6?)

**Comment by IgnitedCoder** [comment]
@solofeed Better API handling and limiting. More Blade features we need for our project. Better variable casting in models ['field' => 'boolean'] so its better for MySQL inserting/updating, UUID is built in & bootstrap 4.

**Comment by RemiCollin** [comment]
@solofeed : also from experience, when you manage a large number of laravel projects, it's more effective to upgrade all your project pool at once, and not leave some projects a few version behind. 

Anyway, for those wanting to upgrade before this PR is merged, you can use my fork by adding this to composer.json : 

`
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/RemiCollin/laravel-mongodb"
        }
    ],
`

**Comment by bojcheski** [comment]
@IgnitedCoder 
Never start a project unless all resources are available.
https://s-media-cache-ak0.pinimg.com/originals/17/bc/49/17bc49b0aa3193b7281f000c5edd3602.jpg

I also did update, but only my dev env, and this is the last step before pushing things live.

**Comment by IgnitedCoder** [comment]
@bojcheski The client determines what I need to do... and this is a new project so I could not tell them what to do, they already had 5.6 installed. :)

**Comment by solofeed** [comment]
I just updated signature in vendor and beginning test application on new version)
And I am still waiting for update deployer for support Symfony 4

**Comment by arthurkirkosa** [comment]
@RemiCollin which tag version from your fork includes this patch?

**Comment by RemiCollin** [comment]
@arthurkirkosa : I didn't tag it. Just use `dev-master` , should work.

**Comment by IgnitedCoder** [comment]
Just for clarity, does dev-master include the 5.6 fixes?

**Comment by Surt** [comment]
I've updated to dev-master and composer does alert about 
 Access level to Jenssegers\Mongodb\Eloquent\Model::getDateFormat() must be public (as in class Illuminate\Database\Eloquent\Model)
during the > @php artisan package:discover

**Comment by IgnitedCoder** [comment]
Yep, not merged... @jenssegers when this merge will happen, please let us know. Sorry to be pushy. :)

**Comment by SelimSalihovic** [comment]
:shipit:

**Comment by drewhammond** [comment]
Shameless bump for merge

**Comment by cherbert** [comment]
Come on! I need this!!

**Comment by jenssegers** [comment]
Merged and tagged!

Thanks so much for your help!

**Pull request merged**
