### PR TITLE
$dates array support

### LINKED ISSUE #109: $date (date-mutators) does not work with dot notation
For example if you try to let it handle `feeds.date`, where `feeds` is an array.

There might not be easy workaround for this one... just reporting for the sake of known limits.

### PR DESCRIPTION
**Pull request by calumks**
Allows you to work with Carbon/DateTime objects instead of MongoDate objects within arrays.

If you specify a full array in $dates, any dates within will be converted into carbon objects. You can also use dot notation to specify dates within arrays.

Works with toArray() and any date that passes through asDateTime().

Resolves #109

### CODE REVIEW

**Comment by spawn-guy** [comment]
this /should/ be supported via embedOne/Many and then no dot-notation would be needed.

and please be careful with `array_set`. 
i created same code recently, and now i have to admit, that `array_set` f*cks up the returned array. 
"last" array's key value is re-written with the last processed (array set) date value :/ (even if it is an array)

i had to rewrite to array_walk_recursive, as a more stable version(i have deadlines over here)

**Comment by erkanarslan** [comment]
This feature is needed +1

**Comment by drewlag** [comment]
News about this?

**Comment by daywong1119** [comment]
I need this function too, hope this can be merge soon

**Comment by Smolevich** [comment]
@jenssegers I think that this old issue should be closed

**Comment by Giacomo92** [comment]
It can be closed @Smolevich @divine . There is also tests [here](https://github.com/jenssegers/laravel-mongodb/blob/master/tests/ModelTest.php#L384)

**Comment by alagaccia** [comment]
So how can you cast to MongoDates something like this?
For example I want to cast date1, date2 from "last_dates" array.

`array('dates' => array(first_dates => array(date1, date2), last_dates => array(date1, date2)))`

**Pull request closed without merging**
