### PR TITLE
Add config for codacy

### PR DESCRIPTION
**Pull request by Smolevich**
- Added `.codacy.yml`

### CODE REVIEW

**Comment by Smolevich** [comment]
@rennokki @divine @Giacomo92 @jenssegers review please

**Comment by Smolevich** [comment]
Button `Merge pull request` is blocked because `At least 1 approving review is required by reviewers with write access` , @jenssegers can you add someone from @divine ,@rennokki, @Giacomo92 to members for repo?

**Comment by Smolevich** [comment]
> Is Codacy something we are looking at adding to this repo?

Снимок экрана 2020-02-07 в 7 32 07

**Comment by Smolevich** [comment]
@divine can you do this PR in another PR and i accept him?

**Comment by Giacomo92** [comment]
I can do also this! @Smolevich

**Pull request closed without merging**
