### PR TITLE
Transaction methods completed.

### PR DESCRIPTION
**Pull request by ilyasokay**
Transaction process required replica set. It will not work in standalone servers.

You can install replica set with codes below; it will not uninstall anything.

> npm install run-rs -g

> run-rs -v 4.0.0 --shell

**Then use replicaSet=rs in your connection.**

Connection details in config/database.php:
```
'mongodb' => [
            'driver' => 'mongodb',
            'host' => env('DB_HOST', 'desktop-nsslhhn'),
            'port' => env('DB_PORT', 27017),
            'database' => env('DB_DATABASE', 'project'),
            'options' => [
                'replicaSet' => 'rs',
            ],
        ],
```

Tested commit and rollback and they worked succesfully. 
    ```
try {

        DB::beginTransaction();

        DB::table('test')->delete();

       // DB::rollBack();

        DB::commit();

    } catch(Exception $e) {

        DB::rollBack();

        throw $e;

    }
```

### CODE REVIEW

**Comment by Smolevich** [comment]
@ilyasokay, add tests plesse

**Comment by Smolevich** [comment]
We need replicaset in ci, if you couldn't implement this, mention me

**Comment by ilyasokay** [comment]
> @ilyasokay, add tests please
> See #1904

I will complete tests as soon as possible. 

> $app['config']

 in TestCase.php is also should be overridden; because rs is not set which is vital.

**Comment by ilyasokay** [comment]
These changes needs to be checked with replica set. When I check containers initialized during test, see nothing but only standalone mongodb. Can anyone help with this?

**Comment by Smolevich** [comment]
> > We need replicaset in ci, if you couldn't implement this, mention me
> 
> These changes needs to be checked with replica set. When I check containers initialized during test, see nothing but only standalone mongodb. Can anyone help with this?

Yes, you can start new instances and сombine in replacaSet https://github.com/jenssegers/laravel-mongodb/blob/master/.github/workflows/build-ci.yml#L18, or copy docker-compose configuration from PR https://github.com/jenssegers/laravel-mongodb/pull/1904

**Comment by ilyasokay** [comment]
Mongo v4+ is required for replica set installation.

**Comment by Smolevich** [comment]
It is not good solution, please add next steps
1. Separate transaction tests in another test group
2. Revert matrix for mongo
3. Add if condition in ci for running transaction tests if mongo > 4

**Comment by ilyasokay** [comment]
All required changes for transaction made but I have some problems with my IDE, sorry for the style...

**Comment by divine** [comment]
Should this really go to master branch @Smolevich?

**Comment by Smolevich** [comment]
> Should this really go to master branch @Smolevich?

I think that we can merge to master, if tests for transactions will be ok

**Comment by ilyasokay** [comment]
> > Should this really go to master branch @Smolevich?
> 
> I think that we can merge to master, if tests for transactions will be ok

I received another error with bulk insert. Bulk insert is not allowed unless the schema exists during mult-document transactions. Let me full check all conditions, if all passes then I would be glad to see this in master branch.

**Comment by ilyasokay** [comment]
Can you please remove this request? I installed my new IDE and I hope I will do everything better.

**Pull request closed without merging**
