### PR TITLE
Convert nested BSONDocument and BSONArray elements

### PR DESCRIPTION
**Pull request by orangeShadow**
Convert nested BSONDocument and BSONArray elements to array

### CODE REVIEW

**Comment by jenssegers** [comment]
Any chance you could add a test for this?

**Comment by orangeShadow** [comment]
Yes,I will do, if you help me. What I must test ? The result is array or equal nesting?

**Comment by divine** [comment]
@orangeShadow any update?

**Comment by divine** [comment]
Closing due to inactivity, free free to create new PR or provide an update here.

**Pull request closed without merging**
