### PR TITLE
Fix embedded relationship on broadcast serialization

### PR DESCRIPTION
**Pull request by gazben**

### CODE REVIEW

**Comment by gazben** [comment]
Related to #397.
If you want to serialize an embedded collection the second parameter will be null, not an empty collection. We need to allow this.

**Comment by gazben** [comment]
Don't merge. The embeds serialization is broken. Help needed

**Comment by spaceemotion** [comment]
@gazben 	We just had this today as well, currently thinking about opening a PR, but the fix is a bit more involved.

The `Collection` parameter is required as it's typehinted by the laravel framework itself. Nothing we can do here.

The real culprit is the `get()` Method on the Relation. The SQL implementations of those always return a collection. This package simply calls the `getResult()` Method which is incorrect for this use case: For 1-1 relationships this returns a single object instead of a collection as all the others do (even the native BelongsTo does this).

It would be more accurate to create a new collection out of it (using the `newCollection` method on the query builder).

Will try to post an initial PR for this tomorrow.

**Comment by spaceemotion** [comment]
Small update: We're having serious issues using this library, as even updates no longer work properly.

1. Create a new embedded instance
2. Set a property on the parent
3. dump() shows everything OK
4. call save()
5. Find the new properly on the embedded instance instead, leaving the original parent's empty.

Looks like this either needs more investigation in our temp. solution to this or the library in general.

**Comment by divine** [comment]
Hello!

Could you please update with the base branch or we can take a look?

Also, @spaceemotion any update?

Thank you for your contribution!

**Comment by divine** [comment]
Closing due to inactivity, free free to create new PR or provide an update here.

**Comment by spaceemotion** [comment]
@divine sorry for not replying earlier. We ended up switching to SQL again, as we had other problems with a NoSQL based architecture, so I never actually ended up working further on that prototype (we did get more issues further down the line with it though, so it was kinda unstable....). Sorry for getting any hopes up!

**Pull request closed without merging**
