### PR TITLE
allow objects to be used in queries

### PR DESCRIPTION
**Pull request by vanhoavn**
This enable support to directly use model's attributes with another model.

### CODE REVIEW

**Comment by jenssegers** [comment]
Can you give an example of how you would use this?

**Comment by vhqtvn** [comment]
hi i’m sorry i didnt receive the notification about this commit.
i already add example in the tests, please take a look, i’ll update here soon.

**Comment by vanhoavn** [comment]
Hi i already provide example usage in the tests:
```php
        $user = new User;
        ...
        $user->address = new Address([
            'name' => 'John Doe',
            'country' => 'Mar',
        ]);
        $user->save();
```
and:
```
$this->assertEquals('John Doe', $user['address.name']);
$this->assertEquals('Mar', $user['address.country']);
```
Basically this just let the driver send native array to mongo insteadof json-ize for things that are Arrayable.

**Comment by vanhoavn** [comment]
the CI test failure is wrong.

**Comment by vanhoavn** [comment]
@jenssegers any problem?

**Comment by vhqtvn** [comment]
@jenssegers can you comment please?

**Comment by vanhoavn** [comment]
@jenssegers please comment

**Comment by vanhoavn** [comment]
Without this, the following case will result in invalid data insert into DB:
```			$user = new User;
			$user->name = 'John Doe';
			$user->title = 'admin';
			$user->age = 35;
			$user->address = new Address([
				'name' => 'John Doe',
				'country' => 'Mar',
			]);
			$user->save();
						
			var_dump(User::get()->toArray());
```

```
array(1) {
  [0]=>
  array(7) {
    ["_id"]=>
    string(24) "5cecb50563e47d461d6aa532"
    ["name"]=>
    string(8) "John Doe"
    ["title"]=>
    string(5) "admin"
    ["age"]=>
    int(35)
    ["address"]=>
    array(4) {
      ["incrementing"]=>
      bool(true)
      ["exists"]=>
      bool(false)
      ["wasRecentlyCreated"]=>
      bool(false)
      ["timestamps"]=>
      bool(true)
    }
    ["updated_at"]=>
    string(35) "Monday 27th of May 2019 09:11:49 PM"
    ["created_at"]=>
    string(35) "Monday 27th of May 2019 09:11:49 PM"
  }
}
```

**Comment by divine** [comment]
Hello!

Could you please update with base branch or we can take a look?

Thank you for your contribution!

**Comment by vanhoavn** [comment]
Hi @divine, I updated.

**Comment by divine** [comment]
If you need this feature just setup laravel relationship and use attach/sync function.

Closing.

**Comment by vhqtvn** [comment]
But in that case it require a new collection created right? This also allow us to type-hint structured properties, directly changing them and update the model without usage of relations.

**Comment by divine** [comment]
@vhqtvn it's up to you on how you solve your problem, decision is final, we aren't going to add this feature.

**Pull request closed without merging**
