### PR TITLE
Created A Docs for Laravel MongoDB Using vitepress(my favorite doc creator)

### PR DESCRIPTION
**Pull request by BroJenuel**
I have been loving laravel MongoDB but I am having problems trying to navigate to the documentation in GitHub. So I started creating my own documentation and want to share it and maybe add it to the repo.

Here is the sample: https://laravel-mongodb.vercel.app/
<details>
<summary> 👔 Deployment:</summary>  

## Deployment   
I recommend deploying it on [VERCEL](https://vercel.com) because it has great support for the `vuejs` environment.
How To Deploy:  
1. Create or Login Account to Vercel.
2. On `https://vercel.com/dashboard` click `add new` and select `project`.
3. In the Import Box, select the branch you like to import.
4. Configure Project
Select Edit for the root directory and select `docs`.
image
And override the other command, and then click the deploy button.
image

5. Setup domain, by going to your project and selecting settings, and click the domain tab. This is were you set the domain name.
6. 
image
</details>

<details>
<summary>How To Edit Doc:</summary>

## How To Edit Docs Page

Once The doc is merged, we can set the GitHub link on the docs config. And a link will show up like the photo below were anyone can edit and create PR. You can check this demo site to see how it works: https://laravel-mongodb.vercel.app/

This is very useful if contributors did an update, they can just go to the docs site, and update the docs easily.

image

</details>

### CODE REVIEW

**Comment by divine** [comment]
Hello,

Sadly, we don't have permission to configure this, see #2499.

Thanks!

**Comment by BroJenuel** [comment]
> Hello,
> 
> Sadly, we don't have permission to configure this, see #2499.
> 
> Thanks!
oh shoot,, thats sad.. what did jenseggers say?

**Comment by alcaeus** [comment]
I'd like to add that such pull requests should also come with maintainer documentation. For example, what's necessary to get this deployed? What kind of tooling must be added to ensure docs are re-generated when they change? Remember that when you're creating a pull request you're not just adding a feature, you're asking the maintainers to take care of that feature in the future. That requires knowledge which this PR does not provide.

**Comment by BroJenuel** [comment]
> I'd like to add that such pull requests should also come with maintainer documentation. For example, what's necessary to get this deployed? What kind of tooling must be added to ensure docs are re-generated when they change? Remember that when you're creating a pull request you're not just adding a feature, you're asking the maintainers to take care of that feature in the future. That requires knowledge which this PR does not provide.

sorry, going to re edit the description of my PR

**Comment by BroJenuel** [comment]
> I'd like to add that such pull requests should also come with maintainer documentation. For example, what's necessary to get this deployed? What kind of tooling must be added to ensure docs are re-generated when they change? Remember that when you're creating a pull request you're not just adding a feature, you're asking the maintainers to take care of that feature in the future. That requires knowledge which this PR does not provide.

I have now Updated the description for more information.

**Comment by divine** [comment]
Sorry, closing it for now. Probably will be taken care in the future.

Thanks!

**Pull request closed without merging**
