### PR TITLE
Fix timestamp errors

### PR DESCRIPTION
**Pull request by zhaff**
1. To generate valid token's timestamp using Carbon

2. To fix error: MongoDB\Driver\Exception\InvalidArgumentException with message 'MongoDB\BSON\UTCDateTime::__construct() expects parameter 1 to be integer, float given'

### CODE REVIEW

**Comment by jenssegers** [comment]
Why is `UTCDateTime` not working?

**Comment by zhaff** [comment]
Yup, its not working, its returning: Uncaught MongoDB\Driver\Exception\InvalidArgumentException: MongoDB\BSON\UTCDateTime::__construct() expects parameter 1 to be integer

Tried these, also not working. I think the easiest way is to use Carbon.

```
$utcdatetime = new MongoDB\BSON\UTCDateTime(round(microtime(true)*1000));

$datetime = $utcdatetime->toDateTime();

var_dump($datetime);

// Return: Uncaught MongoDB\Driver\Exception\InvalidArgumentException: MongoDB\BSON\UTCDateTime::__construct() expects parameter 1 to be integer

$utcdatetime = new MongoDB\BSON\UTCDateTime((int) round(microtime(true)*1000));

$datetime = $utcdatetime->toDateTime();

var_dump($datetime);

// return: 1969-12-24 11:48:21.-164000000"


$utcdatetime = new MongoDB\BSON\UTCDateTime(time());

$datetime = $utcdatetime->toDateTime();

var_dump($datetime);

// return: 1970-01-17 20:15:45.34000000"
```

**Comment by zhaff** [comment]
I just realized the problem is caused by my PHP_INT_MAX is 2147483647. Fyi, I am on windows x86_64. Just hold this PR at the moment.

**Comment by zhaff** [comment]
Tested on homestead, all run just fine. I think only affected on Window.

**Comment by zhaff** [comment]
Cancelled.

**Pull request closed without merging**
