### PR TITLE
Add L5.5 support

### PR DESCRIPTION
**Pull request by MCMatters**
Please review

### CODE REVIEW

**Comment by sagargulati** [comment]
All checks passed! Can you update the repository? So that we can pull the new drivers and the repo? @jenssegers

**Comment by ciruvan** [comment]
@sagargulati @jenssegers All checks pass because this just removes lot of assertions removed from tests, see EmbeddedRelationsTest.php. I'm not sure if this really is the PR we're all hoping for.

**Comment by MCMatters** [comment]
@ciruvan I only removed events from dispatcher because there is a new "retrieved" event which cause problems with tests. I didn't work with Mockery, but I saw in @RemiCollin PR how it can be handled. I updated code, thanks to RemiCollin

**Comment by sagargulati** [comment]
So this is good to go now @MCMatters 
Yes, I saw that but a minor big may help ascertain for a final PR @ciruvan

**Comment by SimplyCorey** [comment]
Awesome work dude, thank you.

**Comment by ciruvan** [comment]
@MCMatters nice work, man! if that PR is accepted by @jenssegers, I owe you one!

**Comment by ConorWright** [comment]
Good job! I've just upgraded to 5.5 and all I'm waiting on is this. Looking forward to it!

**Comment by aashari** [comment]
Thankyou so much @MCMatters this is the solution for all of us, thankyouu... now we're waiting PR accepted by @jenssegers :)

**Comment by sagargulati** [comment]
@jenssegers , when should we expect you will accept the PR by @MCMatters ? :)

**Comment by sagargulati** [comment]
Shouldn't someone update README.md as well? :)

**Comment by MCMatters** [comment]
@sagargulati where exactly do you have an error?

**Comment by sagargulati** [comment]
It's was on belongsToMany. I am using Alpha now and seems it working fine.

**Pull request merged**
