### PR TITLE
[3.8] Laravel 8 support

### PR DESCRIPTION
**Pull request by divine**
- Bump dependencies
- Update test
- Remove PHP 7.2 from github ci
- Remove phpunit ^8.4
- Migrate phpunit configuration (`"Your XML configuration validates against a deprecated schema."`)

For all changes please check https://laravel.com/docs/8.x/upgrade

____

- [x] Queue The **retryAfter** method [hasn't changed](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Queue/DatabaseQueue.php#L41)
- [x] Queue **timeoutAt** property isn't used directly within this library
```php
use Illuminate\Queue\Jobs\DatabaseJob;
class MongoJob extends DatabaseJob
```

- [x] Queue the **allOnQueue()** / **allOnConnection()** methods isn't used directly within this library

### CODE REVIEW

**Comment by divine** [comment]
Only left is https://laravel.com/docs/8.x/upgrade#seeder-factory-namespaces

@Smolevich should we move to new seeder factory namespaces in our tests as well?

**Review by Smolevich — APPROVED** [review]

**Comment by Smolevich** [comment]
> Only left is https://laravel.com/docs/8.x/upgrade#seeder-factory-namespaces
> 
> @Smolevich should we move to new seeder factory namespaces in our tests as well?

I think that we can change this mechanism later

**Comment by Smolevich** [comment]
@jenssegers we drop php 7.2 from matrix because [Laravel](https://github.com/laravel/framework/blob/8.x/composer.json#L18 ) supports php > 7.3, can you off php 7.2 from matrix cache

**Comment by huangdijia** [comment]
+1

**Review by huangdijia — APPROVED** [review]
+1

**Comment by divine** [comment]
> +1

@huangdijia please kindly stop spamming.

**Comment by IsaevDimka** [comment]
@divine when it's released ?

**Comment by Smolevich** [comment]
> @divine when it's released ?

When maintainer(@jenssegers) resolved error with CI

**Comment by divine** [comment]
@Smolevich I think that only collaborators could see this message:

image

-----
@IsaevDimka basically as @Smolevich said we can't merge it* because CI isn't finished and owner of this library needs to disable 7.2 from matrix cache.

\* We don't have enough permissions to do so.

**Review by Smolevich — APPROVED** [review]

**Review by Smolevich — APPROVED** [review]

**Pull request merged**
