### PR TITLE
Issue 1059

### PR DESCRIPTION
**Pull request by doge-dev**
This fixes an ongoing issue https://github.com/jenssegers/laravel-mongodb/issues/1059 - raw queries in Moloquent return arrays, wheres Eloquent raw queries return stdClass objects.

The main reason I created this fix is because further along the line other Laravel libs that are using raw queries might crash (ie Laravel Passport).

I have only nailed down the bugs that emerged in the unit tests.

### CODE REVIEW

**Comment by juanitomint** [comment]
have same issue using mongodb and passport
can I help?

**Comment by fclarat** [comment]
Same Issue!

**Comment by nlattessi** [comment]
Same issue here... Any updates regarding this?

**Comment by arielleguizamon** [comment]
+1

**Comment by xxcynicxx** [comment]
Helfen mir!

**Comment by francodanussi** [comment]
I'm dealing with this problem too

**Comment by imperioame** [comment]
Same here

**Comment by divine** [comment]
Closing due to inactivity, no plans to merge this.

**Pull request closed without merging**
