### PR TITLE
Support laravel 5.3

### PR DESCRIPTION
**Pull request by pi0**
New Laravel queries always return collection. this is a backward compatible enhancement as Collections can be used as Arrays!

**Unfortunately I've lost this fork, so please refer to #905**

### CODE REVIEW

**Comment by lukepolo** [comment]
Should make a new version with these changes exception of the service provider.

**Comment by lukepolo** [comment]
Also , remove deprecated lists.

**Comment by pi0** [comment]
@lukepolo Thanks for mentioning. i'll take a look tonight :)

**Comment by pi0** [comment]
Unfortunately I've lost this fork, so please refer to #905

**Pull request closed without merging**
