### PR TITLE
Revert changes in Builder and Model for id keys, fix test for Queue

### PR DESCRIPTION
**Pull request by Smolevich**
- Fix QueueTest (there is new field `delay` in job payload in core laravel framework)
- Revert changes in [link](https://github.com/jenssegers/laravel-mongodb/pull/1611)

### CODE REVIEW

**Comment by Smolevich** [comment]
@jenssegers, review please

**Comment by AAllport** [comment]
Any idea if active development is on develop or master? Develops seems like it was pushed to last, but master looks... outdated?

**Comment by AAllport** [comment]
Furthermore, it seems like only develop pr's have been accepted?
(Asking as the author of #1794 )

**Comment by Smolevich** [comment]
@AAllport, go to slack. Link [here](https://github.com/jenssegers/laravel-mongodb/issues/1791)

**Pull request merged**
