### PR TITLE
Add matrix for mongodb

### PR DESCRIPTION
**Pull request by Smolevich**
- Create matrix mongodb with versions 3.6, 4.0, 4.2

"Closes: #1918"

### CODE REVIEW

**Comment by jenssegers** [comment]
That coveralls dependency is really being annoying. Might be better to just disable it for now.

**Comment by Smolevich** [comment]
> That coveralls dependency is really being annoying. Might be better to just disable it for now.

We can use case as webonyx (https://github.com/webonyx/graphql-php/commit/599b03b59bf990e289337b1b79dc6aea31ea882e) or use https://github.com/cedx/coveralls.php before accepting this PR https://github.com/php-coveralls/php-coveralls/pull/275

**Comment by Smolevich** [comment]
@jenssegers i add flag `continue-on-error: true` for step with send coveralls

**Comment by jenssegers** [comment]
Awesome!

**Pull request merged**
