### PR TITLE
Check if failed log storage is disabled in Queue Service Provider

### PR DESCRIPTION
**Pull request by robjbrain**
Fixes this issue: https://github.com/jenssegers/laravel-mongodb/issues/2356

### CODE REVIEW

**Review by divine — CHANGES_REQUESTED** [review]
Shouldn't be it something like this and return `NullFailedJobProvider`?
https://github.com/laravel/framework/blob/b9203fca96960ef9cd8860cb4ec99d1279353a8d/src/Illuminate/Queue/QueueServiceProvider.php#L238-L241

**Comment by robjbrain** [comment]
You're right I hadn't spotted that in the original Laravel code

**Review by robjbrain — COMMENTED** [review]
Updated to use Illuminate\Queue\Failed\NullFailedJobProvider

**Comment by robjbrain** [comment]
@divine updated that now

**Comment by divine** [comment]
This won't work as $config is undefined.

**Review by divine — APPROVED** [review]

**Comment by divine** [comment]
Thanks!

**Pull request merged**
