### PR TITLE
Laravel 8 Compatibility

### PR DESCRIPTION
**Pull request by stefnats**

### CODE REVIEW

**Comment by evrend** [comment]
I need Laravel 8 support too. 
I examined Laravel 8 upgrade docs. It seems There's no issue for v8.

**Comment by stefnats** [comment]
Why was this PR closed?

**Comment by Smolevich** [comment]
@stefnats for example you can see on this change https://laravel.com/docs/8.x/upgrade#queue-retry-after-method

**Comment by divine** [comment]
> Why was this PR closed?

I have answered this multiple times. Check my comments over here. This not just a dependency upgrade code changes are required.

Let me remind you, I will push my own PR soon, why you can't just wait?

**Comment by stefnats** [comment]
@Smolevich makes sense, i have not seen this in the upgrade guide

@divine Sorry, i just wanted to learn from mistakes. That's nothing about a hurry. Plenty of other packages are not Laravel 8 ready yet.

Makes sense to not merge in this state.

**Pull request closed without merging**
