### PR TITLE
mongo objectID for the relations

### PR DESCRIPTION
**Pull request by RTLer**
I make some changes to make this driver work with object id.
also, because some database still use mongoID as string for relations I add options to use objectID or not (default  is not).

```php
 'mongoid' => true, // sets to use mongoID object instead of mongoID as string in relations.
```

### CODE REVIEW

**Comment by sirago** [comment]
Can we get this implemented? Relationships should use MongoId.

**Comment by amiri27** [comment]
+1 it.. nice implementation..

**Comment by jenssegers** [comment]
Currently reviewing your PR. Will probably have to tag a new major version though.

**Comment by amiri27** [comment]
@jenssegers any update on this?

**Comment by RTLer** [comment]
@jenssegers, 
thx for reviewing this PR, I was Busy on some project
really want to see this in action, there is any thing i can do to help?

**Comment by amiri27** [comment]
@RTLer Could you please solve the conflicts?

**Comment by gnrcampos** [comment]
Any progress on this? Depending on this merge to do some things, can I help in any way?

**Comment by jenssegers** [comment]
Well thing is, the new v3 release will bring support for the new mongodb PHP driver. I feel like doing both the driver and the mongo id's at the same time will break too many applications.

Current plan is to release v3 soon with the new driver, and work on a v4 featuring the mongo id's.

**Comment by jenssegers** [comment]
Also; because of the new mongodb driver, this PR is a bit outdated. So I can't really merge it into master.

**Comment by RTLer** [comment]
see #834

**Pull request closed without merging**
