### PR TITLE
 Add MorphMany relation to replaced whereIn method.

### PR DESCRIPTION
**Pull request by Majed6**
A mere rebase of https://github.com/jenssegers/laravel-mongodb/pull/1776 . See that PR for details

### CODE REVIEW

**Comment by Smolevich** [comment]
Merge actual master

**Comment by Majed6** [comment]
Just did. @Smolevich Could you please advise me on Codacy & StyleCI checks ?

**Comment by rennokki** [comment]
@Majed6 I assume your use case is a model that extends the mongo model and has `$keyType` set to integer and the key name is not `_id`? Because i seek for the `whereInMethod` across the relations, and it seems like this is the line where it might use `whereIntegerInRaw` and not `whereIn`, right? 

https://github.com/laravel/framework/blob/6.x/src/Illuminate/Database/Eloquent/Relations/Relation.php#L317

**Comment by Majed6** [comment]
@rennokki  I apologize for the delayed response. I'm using mongodb with  [ owen-it /
laravel-auditing ](https://github.com/owen-it/laravel-auditing) and the function `with('audits')` did not work for me with audited models until I applied this change.

**Comment by rennokki** [comment]
@Majed6 Merge with the current `master` branch.

**Comment by Majed6** [comment]
@rennokki  Just did. Will this get merged anytime soon ?   😄

**Comment by rennokki** [comment]
@Smolevich

**Comment by Majed6** [comment]
Hooray 🎉 . Thanks y'all.  Don't forget to close this [Duplicate PR](https://github.com/jenssegers/laravel-mongodb/pull/1816)

**Pull request merged**
