### PR TITLE
[3.x] add escape regex chars to DB Presence Verifier

### PR DESCRIPTION
**Pull request by andrei-gafton-rtgt**
add preg_quote to value in getCount for Unique validation with DatabasePresenceVerifier.php in order to correctly escape regex chars in values from DB (eg. "+")

### CODE REVIEW

**Comment by jenssegers** [comment]
# [Codecov](https://codecov.io/gh/jenssegers/laravel-mongodb/pull/1992?src=pr&el=h1) Report
> Merging [#1992](https://codecov.io/gh/jenssegers/laravel-mongodb/pull/1992?src=pr&el=desc) into [master](https://codecov.io/gh/jenssegers/laravel-mongodb/commit/279b18c7686b6da28ce4b278c9e34978ad3fd497&el=desc) will **not change** coverage by `%`.
> The diff coverage is `100.00%`.

[Impacted file tree graph](https://codecov.io/gh/jenssegers/laravel-mongodb/pull/1992?src=pr&el=tree)

```diff
@@            Coverage Diff            @@
##             master    #1992   +/-   ##
=========================================
  Coverage     86.75%   86.75%           
  Complexity      666      666           
=========================================
  Files            31       31           
  Lines          1518     1518           
=========================================
  Hits           1317     1317           
  Misses          201      201           
```


| [Impacted Files](https://codecov.io/gh/jenssegers/laravel-mongodb/pull/1992?src=pr&el=tree) | Coverage Δ | Complexity Δ | |
|---|---|---|---|
| [...rs/Mongodb/Validation/DatabasePresenceVerifier.php](https://codecov.io/gh/jenssegers/laravel-mongodb/pull/1992/diff?src=pr&el=tree#diff-c3JjL0plbnNzZWdlcnMvTW9uZ29kYi9WYWxpZGF0aW9uL0RhdGFiYXNlUHJlc2VuY2VWZXJpZmllci5waHA=) | `76.92% <100.00%> (ø)` | `7.00 <0.00> (ø)` | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/jenssegers/laravel-mongodb/pull/1992?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/jenssegers/laravel-mongodb/pull/1992?src=pr&el=footer). Last update [279b18c...eae84ce](https://codecov.io/gh/jenssegers/laravel-mongodb/pull/1992?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by Smolevich** [comment]
> …h regex

@andrei-gafton-rtgt, Update description please

**Comment by Smolevich** [comment]
@andrei-gafton-rtgt add additional test case for this PR

**Comment by divine** [comment]
@Smolevich anything is left here?

**Review by divine — APPROVED** [review]

**Review by Smolevich — APPROVED** [review]

**Pull request merged**
