### PR TITLE
Fix dropIndex for compound indexes with sorting order

### PR DESCRIPTION
**Pull request by mauri870**
It's not possible to drop an index with a descending sorting order, because the library assumes an ascending order. If no order is given to the field, the default order is used.

### CODE REVIEW

**Comment by Smolevich** [comment]
@mauri870 add description please

**Comment by mauri870** [comment]
Description updated @Smolevich

**Comment by rennokki** [comment]
This repo seems like it gets slow updates. Would you mind switching for https://github.com/rennokki/laravel-mongodb and submitting this PR down there?

**Comment by Smolevich** [comment]
@mauri870 tests failed, check please

**Comment by mauri870** [comment]
@Smolevich Can you take  a look at the failing test? Can't find the cause of the error.

**Comment by Smolevich** [comment]
> @Smolevich Can you take a look at the failing test? Can't find the cause of the error.
See 
https://github.com/jenssegers/laravel-mongodb/pull/1885/checks?check_run_id=425253804

**Comment by mauri870** [comment]
@Smolevich All tests passing

**Comment by Giacomo92** [comment]
Can you merge actual master, please? @mauri870

**Pull request merged**
