### PR TITLE
Add auto-increment _id support

### PR DESCRIPTION
**Pull request by Gtskk**
Add auto-incrementing _id support.

With the value of `incrementing` property, you can easily enable or disable the auto-incrementing  _id support.

**Note:** By default, the function is enabled. You can set `incrementing=false` to disable the function.

PS: Forgiving my poor English.

### CODE REVIEW

**Comment by RTLer** [comment]
adding auto-incrementing id to mongo like this, is not good idea considering race condition
it can cause duplicate key error.

**Comment by Gtskk** [comment]
@RTLer  And a better solution?

**Comment by RTLer** [comment]
i use redis to to generate true incremental id.

**Comment by amiri27** [comment]
@Gtskk auto_increment using mongodb is not safe with race conditions. You can use redis cache to auto_increment indexes which is safe regarding race conditions.

**Pull request closed without merging**
