### PR TITLE
add templates for issues

### LINKED ISSUE #1912: Add templates for issues
I propose to add templates for creating new issues. [Docs](shttps://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository)

### PR DESCRIPTION
**Pull request by Smolevich**
- Add templates for issues

closes #1912

### CODE REVIEW

**Comment by Smolevich** [comment]
@divine @rennokki @Giacomo92 @jenssegers 
For contibuting we can discuss about format. For example https://github.com/laravel/framework/blob/6.x/.github/CONTRIBUTING.md
https://github.com/telegramdesktop/tdesktop/blob/dev/.github/CONTRIBUTING.md

**Comment by Giacomo92** [comment]
Check also this https://github.com/spatie/laravel-event-sourcing/blob/master/CONTRIBUTING.md. I think it is shorter to read. I would also add a link to [this](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork) (also present on telegram link of Smolevich)

**Comment by Smolevich** [comment]
@divine, @Giacomo92  can you to do this PR in another?

**Comment by Giacomo92** [comment]
I can do it @Smolevich

**Pull request closed without merging**
