### PR TITLE
Backport of issue #2127 to tree 3.6

### PR DESCRIPTION
**Pull request by pendexgabo**
Hello!

first off, thank you for your hard work on this project!

This MR is a "backport" (mostly a C&P) from the issue 2127 to the tree 3.6. 

We are running into the same issue with the version in laravel 6.x

### CODE REVIEW

**Comment by divine** [comment]
Hello,

First of all, thank you for your contribution.

Yes, we know about this problem and I was planning to update it.

Can you push another PR to backport also for 3.7, otherwise it might become a mess with releases.

Thanks!

**Comment by pendexgabo** [comment]
@divine Please take a look to https://github.com/jenssegers/laravel-mongodb/pull/2131

**Comment by divine** [comment]
@pendexgabo thank you for your help!

We do really appreciate your help, I will release new version _soon_.

Thanks!

**Comment by pendexgabo** [comment]
Thanks! credit goes to @hnassr

**Comment by divine** [comment]
> Thanks! credit goes to @hnassr

Yes, but backporting is also a work that you've done and you know it takes time!

Thanks!

**Pull request merged**
