### PR TITLE
Replaced whereIn method retrieval for relations

### PR DESCRIPTION
**Pull request by Zuken**
Replaced whereIn method retrieval for relations, to force use standart whereIn instead of whereInRawInteger.

### CODE REVIEW

**Comment by Zuken** [comment]
@marcnewton Please check this solution for #1659

**Comment by marcnewton** [comment]
@Zuken Yes, that looks like relationship id's are now getting set. Nice

**Comment by iocaste** [comment]
@jenssegers Can you accept this please ?

**Comment by rennokki** [comment]
Maybe tagging a new release?

**Comment by SelimSalihovic** [comment]
@jenssegers Is this going out in a new release soon? We desperately need it. I assume others do as well.

**Comment by SelimSalihovic** [comment]
@jenssegers Quick Draw Jens. Thanks man 🍻

**Pull request merged**
