### PR TITLE
Apply fixes from StyleCI

### PR DESCRIPTION
**Pull request by simonschaufi**
This pull request applies code style fixes from an analysis carried out by [StyleCI](https://github.styleci.io).

### CODE REVIEW

**Comment by simonschaufi** [comment]
Somehow I get the following error here but when I execute the checks in my fork, they are all green:

```
Config Issue
The risky 'empty_return' fixer cannot be enabled because risky mode is not enabled.
```

**Comment by divine** [comment]
Hello,

Well, we've about 4-5 PRs that awaiting merging and it will make things messy a bit.

My personal view that we need to drop this styleci and move on to php-cs-fixer. I will probably take care of it.

They've banned my account for no reason (used only on my laravel-mongodb fork) and the whole service run by a kid who doesn't reply to emails (lol?).

Thanks!

**Comment by simonschaufi** [comment]
@GrahamCampbell Can you give some insights on what is going on?

**Comment by divine** [comment]
> @GrahamCampbell Can you give some insights on what is going on?

Hello,

He won't reply (>1 year without reply), I promise you because it doesn't make sense to delete the account and don't give a reason.

I don't really care about his service and never heard of this styleci before Laravel so not interested in restoring the account.

This was just a kindly reminder that we should stay away from such services when there is an open-source self-hosted alternative that is much better. 

image

Thanks!

**Comment by GrahamCampbell** [comment]
You should be able to sign up for a fresh account. If you think the account was deleted in error, please let me know. The most common reason for automated account deletion was removal of StyleCI's access on GitHub - their terms of service for integrators binds StyleCI to delete the account, just like an unsubscribe request for an email.

**Comment by simonschaufi** [comment]
@GrahamCampbell thank you for your quick reply but I was actually asking about the error in styleci. I guess you can give some insight how to fix the error. Thank you!

**Comment by GrahamCampbell** [comment]
> The risky 'empty_return' fixer cannot be enabled because risky mode is not enabled.

Possibly you have config set in the web interface. If you do this, any config file in the repo will be ignored.

**Comment by GrahamCampbell** [comment]
Yes, this seems to be the case:

image

**Comment by divine** [comment]
> You should be able to sign up for a fresh account. If you think the account was deleted in error, please let me know. The most common reason for automated account deletion was removal of StyleCI's access on GitHub - their terms of service for integrators binds StyleCI to delete the account, just like an unsubscribe request for an email.

@GrahamCampbell it's indeed was deleted.

Never mind, can you enable risky mode for this repo so we won't see that error?

Thanks!

**Comment by simonschaufi** [comment]
@divine I would suggest to remove the config in the web interface and use the one from the repo. Then we have full control over it

**Comment by divine** [comment]
> @divine I would suggest to remove the config in the web interface and use the one from the repo. Then we have full control over it

Hello @simonschaufi ,

I'm really sorry we can't remove it - no access. Please see https://github.com/jenssegers/laravel-mongodb/pull/2090#issuecomment-685314024

Thanks!

**Comment by simonschaufi** [comment]
@divine I thought that @GrahamCampbell could do it as he is a system admin ;)

**Comment by GrahamCampbell** [comment]
I've removed that config for you.

NB StyleCI should not be enabled on forks for the purpose of analyzing PRs. Instead, auto-fixing should be enabled, so code from forks is fixed after merge, like on Laravel.

**Comment by divine** [comment]
> I've removed that config for you.
> 
> NB StyleCI should not be enabled on forks for the purpose of analyzing PRs. Instead, auto-fixing should be enabled, so code from forks is fixed after merge, like on Laravel.

Hello,

We don't have ability or permission for auto-merging and communication is lost as you could see.

Thank you for fixing configuration that was broken.

Thanks!

**Comment by GrahamCampbell** [comment]
I'd recommend asking the owner of this repo to move it to an organisation on GitHub and giving the new maintainers admin access, so they can properly maintain the repo. Repos attached to single users were not designed to have multiple core maintainers.

**Pull request closed without merging**
