### PR TITLE
Add MustVerifyEmail

### PR DESCRIPTION
**Pull request by si2w**
Added support for Laravel authentication when users need to check their emails to connect

### CODE REVIEW

**Comment by nicolasyousician** [comment]
Not everyone needs this trait though. Also I think Laravel doesn't ship with it out of the box.

**Comment by Christophvh** [comment]
@nicolasyousician, It does.

**Comment by narwy** [comment]
`MustVerifyEmail` is a trait provided as standard by Laravel in any install.

**Comment by divine** [comment]
Hello!

Could you please update with the base branch or we can take a look?

Thank you for your contribution!

**Comment by Smolevich** [comment]
@si2w merge actual master please

**Comment by Smolevich** [comment]
Looks like that we extend this class https://github.com/laravel/framework/blob/1bbe5528568555d597582fdbec73e31f8a818dbc/src/Illuminate/Foundation/Auth/User.php

**Pull request merged**
