### PR TITLE
Fixes #789

### LINKED ISSUE #789: Artisan queue [failed] [retry] do not work as expected
**artisan queue:failed** 
Does not work because the failed_at column is not stored as a timestamp.
Exception thrown: strstr() expects parameter 1 to be string, array given 

**artisan queue:retry id** 
Does re queue the job but does not delete the record in the failed_jobs collection.
Exception thrown: Undefined property: stdClass::$id

**artisan queue:retry all** 
Does not find any failed jobs even when there are some present.
Error: No failed job matches the given ID [].

### PR DESCRIPTION
**Pull request by Bodom78**
Docs updated with required information to use MongoDB for failed jobs.

Artisan queue failed, retry with id and retry all now work as expected.

### CODE REVIEW

**Comment by Bodom78** [comment]
I don't understand why StyleCI analysis is failing when it just reports a close brace is to be replaced with a close brace?

**Comment by pi0** [comment]
@Bodom78 StyleCI fails because it should be an empty line at the end of file :)

**Comment by pi0** [comment]
@Bodom78 StyleCI fails because it should be an empty line at the end of file :)

**Comment by Bodom78** [comment]
@pi0 Thanks for that.

**Comment by pi0** [comment]
There are breaking changes on master so unitTests are failing. would you please follow [This](https://github.com/jenssegers/laravel-mongodb/issues/937) steps to rebase this PR with master branch and running UnitTests against latest changes ?

Thanks :)

**Pull request merged**
