### PR TITLE
Added laravel 8 support

### PR DESCRIPTION
**Pull request by rakeshlanjewar**
Hello, 
        I have updated current dependencies to laravel 8 dependencies to the project. I have not fully tested it.
        Thank you.

### CODE REVIEW

**Comment by clipvui2512** [comment]
not work on php 7.2.xxx
just add requires php >=7.3

**Comment by rakeshlanjewar** [comment]
For those who want to use this library on laravel 8. Not tested but working for me. I don't advice to use it, it may break your application.

1. clone this repo
2. change the composer.json of this package according to your application
3. in your application's composer.json use it as local repo. 

```
"require": {
        "jenssegers/mongodb" : "*"
    },
 "repositories": [
    {
            "type": "path",
            "url": "{{path to repo, example: ~/home/laravel-mongodb }}"
        }
    ],
```

**Comment by divine** [comment]
@rakeshlanjewar I'm really sorry but did you read correctly my previous comments over here?

I'm not really sure what are you trying to say if you really wanted Laravel 8 then basically your tests would be passing in this PR. You didn't have a chance even to update test bench.

**Comment by clipvui2512** [comment]
> For those who want to use this library on laravel 8. Not tested but working for me. I don't advice to use it, it may break your application.
> 
> 1. clone this repo
> 2. change the composer.json of this package according to your application
> 3. in your application's composer.json use it as local repo.
> 
> ```
> "require": {
>         "jenssegers/mongodb" : "*"
>     },
>  "repositories": [
>     {
>             "type": "path",
>             "url": "{{path to repo, example: ~/home/laravel-mongodb }}"
>         }
>     ],
> ```
> 
> I may not doing this, but i am not sure when the laravel 8 support will be released, i am following the development and i found that laravel 7 support was released this week.

you need 

    "require": {
        "php": ">7.2.5",

**Comment by rakeshlanjewar** [comment]
> @rakeshlanjewar I'm really sorry but did you read correctly my previous comments over here?
> 
> I'm not really sure what are you trying to say if you really wanted Laravel 8 then basically your tests would be passing in this PR. You didn't have a chance even to update test bench.

Ignore this PR for now , I will work on this when i will get time. And sorry for the bad English (;

**Comment by divine** [comment]
> > @rakeshlanjewar I'm really sorry but did you read correctly my previous comments over here?
> > I'm not really sure what are you trying to say if you really wanted Laravel 8 then basically your tests would be passing in this PR. You didn't have a chance even to update test bench.
> 
> Ignore this PR for now , I will work on this when i will get time. And sorry for the bad English (;

You still haven't read my comments over here. I have done some work for L8. Awaiting L7 after that I could push PR.

This isn't about your bad English, it's about patience.

**Comment by evrend** [comment]
You can use this package with Laravel 8. But some issues must be solved for Laravel 8. Attention: If you will use this package with queue operations then you must be careful. I'm using it but I will upgrade it when it has Laravel 8 support.
https://github.com/jenssegers/laravel-mongodb/pull/2104#issuecomment-695051102

Using with Laravel 8:
Copy the package to your project.

    Your Laravel Project
    ├── ...
    ├── packages                      # You can change directory name with your preferred.
    │   ├── laravel-mongodb
    │   |  ├── src/Jenssegers/Mongodb
    └── ...

Change package name and add Laravel 8 support: `packages\laravel-mongodb\composer.json`

```json
{
"name": "your-package/laravel-mongodb",
...
    "require": {
        "illuminate/support": "^7 || ^8",
        "illuminate/container": "^7 || ^8",
        "illuminate/database": "^7 || ^8",
        "illuminate/events": "^7 || ^8",
        "mongodb/mongodb": "^1.6"
    },
...
}
```

Change package name: `packages\laravel-mongodb\composer.json`

```json
{
"name": "your-package/laravel-mongodb",
...
}
```

Add the local repo to your Laravel project's `composer.json`
```json
{
...
    "repositories": {
        "mongodb": {
            "type": "path",
            "url": "packages/laravel-mongodb",
            "options": {
                "symlink": true
            }
        }
    },
...
}
```

Add the local repo to requirements
```json
{
...
"require": {
        "your-package/laravel-mongodb": "dev-master",
        ...
    },
...
}
```

Run `composer update` command
```bash
composer update
```

You can examine documents about Laravel package development.
https://mauricius.dev/require-a-local-composer-package-for-development/
https://pineco.de/laravel-package-development-basics/

**Comment by tairau** [comment]
@evrend so hard.
Just fork repo, do what you want - update illuminate dependencies and etc.
And add this
```
"repositories": [
        {
            "type": "git",
            "url": "git@github.com:<YOUR NICKNAME HERE>/laravel-mongodb.git",
            "vendor-alias": "jenssegers/mongodb"
        }
    ],
```
to your composer.json

and now you can install your fork without more manipulation and replacement package name

`composer require jenssegers/mongodb` or `composer update`

Sorry for offtop.

<details>
  <summary>Screenshots under cut</summary>
  
Снимок экрана 2020-09-21 в 21 21 55
Снимок экрана 2020-09-21 в 21 20 53

</details>

**Comment by evrend** [comment]
@tairau Thanks for the simple alternative method.
I create all my Laravel applications as package. So, I'm used to this method.
I tried your method but I couldn't be successful. I used endpoint like so:  `https://github.com/evrend/laravel-mongodb.git`'. I will fork again and will retry it with so: `git@github.com:evrend/laravel-mongodb.git`

**Comment by tairau** [comment]
@evrend maybe this only works with composer 2

**Pull request closed without merging**
