### PR TITLE
Change travis ci 

### PR DESCRIPTION
**Pull request by Smolevich**
- Remove using docker compose configuration and files linked with her
- Add configuration for travis with custom mongo daemon
- Change composer.json 

I can use services in travis ci, but there is old version (3.4.10) for service mongodb and itsn't possible to change version. See https://github.com/travis-ci/travis-ci/issues/7614. @jenssegers, If you don't agree with using non-docker configuration for tests, i can revert configuration with docker. Configuration with running tests without docker services faster because build custom container take more time (If use ready docker images jobs can faster). We can cache vendor files and composer cache with this configuration

### CODE REVIEW

**Comment by Smolevich** [comment]
@jenssegers, can you review please?

**Comment by jenssegers** [comment]
These are a lot of changes in 1 PR. From what I hear, your main issue is that the mongodb installation on Travis is an old version? I'll look into fixing one problem at a time :)

**Comment by Smolevich** [comment]
I can new PR with last changes in one commit.

**Comment by Smolevich** [comment]
@jenssegers, i created new [PR](https://github.com/jenssegers/laravel-mongodb/pull/1732) with this changes

**Pull request closed without merging**
