### PR TITLE
Unset field

### PR DESCRIPTION
**Pull request by halaei**
This Changes the way fields are unset, so that by a single update query, changes fields get updated and unset fields get removed from the document.

### CODE REVIEW

**Comment by halaei** [comment]
This PR includes PR #1664 and is backward incompatible as well.

**Comment by halaei** [comment]
It also covers #1468.

**Comment by divine** [comment]
Hello!

Could you please take care for conflicting file or we can take a look?

Thank you for your contribution!

**Comment by divine** [comment]
Hi there,

This PR contains a breaking change and will be released within next version.

Closing for now.

Thanks.

**Comment by halaei** [comment]
@divine I am glad this project became active. I'll send a PR within a day.

**Pull request closed without merging**
