### PR TITLE
Fix Laravel 9.31 breaking update

### PR DESCRIPTION
**Pull request by The-Hasanov**
Issue #2451

### CODE REVIEW

**Comment by fosron** [comment]
@The-Hasanov thank you for your solution 🙇 

@Smolevich can we get this into a release soon? It's a breaking change for L9. Thanks 🙏

**Review by Smolevich — APPROVED** [review]

**Comment by The-Hasanov** [comment]
> Hi all. First of all apologies that things broke for this library. I'd like to know more about what happened here. Why are string keys incremental for MongoDB?

Problem is here [https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Eloquent/Model.php#L1209](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Eloquent/Model.php#L1209)
so can see model not get mongo string id after create

**Comment by driesvints** [comment]
> > Hi all. First of all apologies that things broke for this library. I'd like to know more about what happened here. Why are string keys incremental for MongoDB?
> 
> Problem is here https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Eloquent/Model.php#L1209 model not get string uuid after create

Heya. I realize that but given it's a string based ID, the ID should be set as an attribute up front. Is MongoDB not doing that? How are ID's generated now?

**Comment by The-Hasanov** [comment]
i don't know about technical side. But id or _id is generated on mongo side automatically. Also this id is unique and incremental.

**Comment by driesvints** [comment]
Thanks for that. I've sent in a PR to framework to revert this change: https://github.com/laravel/framework/pull/44247

**Comment by alcaeus** [comment]
> Is MongoDB not doing that? How are ID's generated now?

The MongoDB server will add an `_id` field and generate an [ObjectId](https://www.mongodb.com/docs/manual/reference/bson-types/#std-label-objectid) for it if a document being inserted does not contain one. In addition to that, the MongoDB driver for PHP will also create an ObjectId when inserting a document without an `_id` field. If an application wants to use a different key (e.g. a UUID), this has to be created on the application side before passing the document on to the driver.

**Comment by fosron** [comment]
Thank you @driesvints 🙇‍♂️

**Pull request closed without merging**
