### PR TITLE
Update for Laravel 5.5

### PR DESCRIPTION
**Pull request by SimplyCorey**
This updates the `belongsToMany` signature for Laravel 5.5

See: https://laravel.com/docs/5.5/upgrade

### CODE REVIEW

**Comment by SimplyCorey** [comment]
Laravel support is going to need to be bumped to 5.5 in the composer.json file.  Not sure how you want to handle that.

**Comment by RemiCollin** [comment]
Nope, checks the composer.json, version constraint is `^5.1`, so it will not prevent installing it from a 5.5 version. 

What we might need is to tag a new package version (3.3 ?) to reflect the breaking change.

**Comment by akaroot** [comment]
see PR #1282

**Comment by SimplyCorey** [comment]
3.3 would also have to drop support for php5.6 in the test suite.

**Comment by SimplyCorey** [comment]
Closing in favor of: https://github.com/jenssegers/laravel-mongodb/pull/1300

**Pull request closed without merging**
