### PR TITLE
Use MongoId for relations

### PR DESCRIPTION
**Pull request by philipbrown**
Hi @jenssegers 

I'm looking to add the functionality to use `MongoId` instances for relations.
- #356
- #350 
- #134

This will be a work in progress PR. If you have any ideas on how this should be implemented, please let me know :smile:

### CODE REVIEW

**Comment by philipbrown** [comment]
Ah screw it, ignore this :stuck_out_tongue:

**Comment by Alain1405** [comment]
Any news on this?

**Comment by jenssegers** [comment]
Not yet, I might give it another try for the v3 release once I get the embedded models working again.

**Comment by Alain1405** [comment]
Thanks!

**Comment by ScottSpittle** [comment]
Update on this? It's a blocker for me moving over fro MogoLid. :D

**Comment by jenssegers** [comment]
No update on this yet. The way Eloquent is written requires a lot of the relation code to be rewritten. Still need to find a proper approach to the problem.

**Comment by ScottSpittle** [comment]
Ok thanks for the reply, I'll check back another time :D Good work!

**Comment by devcodebakerz** [comment]
Is there any update on this ?

**Pull request closed without merging**
