### PR TITLE
Fixed Error "Cannot use object of type MongoDB\BSON\UTCDateTime as array"

### PR DESCRIPTION
**Pull request by nolanle**
When I reset password with token but have error like "Cannot use object of type MongoDB\BSON\UTCDateTime as array"
And this is solution for fix it.
Thanks alot!

### CODE REVIEW

**Comment by arthurkirkosa** [comment]
@jenssegers this does solve the reset password problem because of laravel latest changes.

**Comment by arunmisra2273** [comment]
I get error Parse error: syntax error, unexpected 'if' (T_IF) when I use this fix

**Comment by arunmisra2273** [comment]
works. Thank you! @nolanle

**Comment by mikekamornikov** [comment]
@jenssegers There are at least 3 issues/prs here with "reset password" fix. Could you merge this (or any other) one?

**Comment by koAndy** [comment]
@jenssegers Tested and worked! Please merge this!

**Pull request merged**
