### PR TITLE
Recursive Convert Dates In Where Clause

### PR DESCRIPTION
**Pull request by deividaspetraitis**
see #913

### CODE REVIEW

**Comment by deividaspetraitis** [comment]
Can't get what's wrong with build? And how queue is related with mine fix?

**Comment by sakalauskas** [comment]
It's not you. That queue test always fails in all builds 😃

**Comment by deividaspetraitis** [comment]
That's weird. @jenssegers ?

**Comment by pi0** [comment]
There are breaking changes on master so unitTests are failing. would you please follow [This](https://github.com/jenssegers/laravel-mongodb/issues/937) steps to rebase this PR with master branch and running UnitTests against latest changes ?

Thanks :)

**Pull request merged**
