### PR TITLE
Add job queue support for mongodb.

### PR DESCRIPTION
**Pull request by jeremy-brenner**
This adds job queue support by making a few small changes to the Database job queue libraries.  It has a separate service provider making it's usage completely optional.

### CODE REVIEW

**Comment by CurosMJ** [comment]
Instead of having a `table` config parameter, we should have a `collection` parameter, since this is Mongo.

**Comment by CurosMJ** [comment]
And, why not have a seperate `mongodb` queue driver, instead of extending the database driver?

**Comment by jeremy-brenner** [comment]
It isn't a driver per se.  The 'database' setting uses whatever database driver Laravel is already using.  If you set your queue driver to database while the laravel-mongodb driver is in use it will try to use your mongo database and fail.  This really just patches it so that it can work as intended.  I have not really looked at how the other queues are implemented but since mongodb isn't really a queue then I doubt anybody would want a standalone mongodb queue while using some other database as default laravel db driver.  That is my reasoning anyway. :)

**Comment by johngieselmann** [comment]
Any progress?

**Comment by jenssegers** [comment]
@jeremy-brenner What did you change in the `MongoQueue` class? It looks almost identical as the `DatabaseQueue` class.

**Comment by leakingminds** [comment]
Any news on this? Does it work?

**Comment by jenssegers** [comment]
Currently waiting one @jeremy-brenner's response.

**Comment by leakingminds** [comment]
hmm... ok well, since this post is pretty old, i guess there wont be any response... 
has anyone tried it out yet? i havent really worked with qeues, so i cant confirm this!

**Comment by jeremy-brenner** [comment]
The difference is that Mongo can't "select for update" so it was replaced with a simple loop.  As for the naming, the "database" and "table" nomenclature was kept because really the "database" driver has nothing to do with the db and really means "use the ORM" which in this case happens to be Moloquent rather than Eloquent.  If I switch then name then I have to do a little bit of redirecting instead of just using the ORM directly like it already does.  It's a trivial difference so I left it.  It works fine, I use it personally.  I have not done a recent merge and test but I use it in a couple projects.

**Comment by leakingminds** [comment]
Sweet! Pretty excited to try it out :)

One more question, which i didnt really understand from your post: Do you use Eloquent or Moloquent for this?

**Comment by jeremy-brenner** [comment]
This is a simple connector to make job queues work with Moloquent.  It just adds the necessary files and makes no changes to Moloquent directly.  You just need to load them as outlined in the docs to make it work.

**Comment by jeremy-brenner** [comment]
Is there any more I can do to help this go more smoothly?  Any other outstanding questions that I have not covered?

**Comment by jenssegers** [comment]
I prefer extending original Laravel classes rather than copy pasting all their code. So I need to figure out what was changed before I can create an extended class. Or if you want to refactor your code that's good as well :)

**Comment by jeremy-brenner** [comment]
The issue is pretty straightforward.  
In releaseJobsThatHaveBeenReservedTooLong in Illuminate/Queue/DatabaseQueue.php the query chains an update.  This doesn't work with mongo. 

    protected function releaseJobsThatHaveBeenReservedTooLong($queue)
    {
        $expired = Carbon::now()->subSeconds($this->expire)->getTimestamp();

        $this->database->table($this->table)
                    ->where('queue', $this->getQueue($queue))
                    ->where('reserved', 1)
                    ->where('reserved_at', '<=', $expired)
                    ->update([
                        'reserved' => 0,
                        'reserved_at' => null,
                        'attempts' => new Expression('attempts + 1'),
                    ]);
    }

Thats really it.  I tried extending the Illuminate classes but had little luck.  Another approach might be to simply emulate the ->update() behavior in the db driver leaving the database queue driver alone entirely.

**Comment by jenssegers** [comment]
Thanks @jeremy-brenner, I have added your code using an extending class in my latest commits.

**Comment by leakingminds** [comment]
Nice, that was fast :)

How about using and setting everything else up? Is it basically the same as:

https://laravel.com/docs/5.1/queues

Nothing else to keep in mind?

Thanks guys!

**Comment by jenssegers** [comment]
@leakingminds I updated the readme as well.

**Pull request closed without merging**
