### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by simonschaufi**
Apply code cleanup suggested by PhpStorm Plugin:  https://github.com/kalessil/phpinspectionsea

* Made tests of type strict type
* added lots of annotations and return types for better IDE (color) support

This is my way of saying thank you for that great package!

### CODE REVIEW

**Comment by Smolevich** [comment]
@simonschaufi, please join into slack channel. Link [here](https://github.com/jenssegers/laravel-mongodb/issues/1791)

**Comment by simonschaufi** [comment]
@Smolevich ok, I'm in. you can find me with "Simon"

**Comment by simonschaufi** [comment]
@Smolevich ok, I'm in. you can find me with "Simon"

**Comment by jenssegers** [comment]
Awesome!

**Pull request merged**
