### PR TITLE
Added support for "whereAll" queries

### PR DESCRIPTION
**Pull request by lindelius**

### CODE REVIEW

**Comment by lindelius** [comment]
Can we get this reviewed and merged, please? @jenssegers

**Comment by lindelius** [comment]
Thanks!

**Comment by GromNaN** [comment]
Why did you need this method @lindelius?

Both
```php
->where('tags', 'all', ['ssl', 'security'])
```
and
```php
->whereAll('tags', ['ssl', 'security'])
```

Produced the same MongoDB query
```ts
{ tags: { $all: ["ssl", "security"] } }
```

**Comment by lindelius** [comment]
Not really, I haven't used the library for years, but it was problaby because there was either no other way to do it back then or that I just wanted a nicer way to do it than to explicitly have to type the "all" parameter. I really can't remember, though. Sorry.

**Comment by lindelius** [comment]
FWIW, the projects I worked on back then are no longer using the method

**Comment by GromNaN** [comment]
Thanks for checking.

**Pull request merged**
