### PR TITLE
Dynamically cast and set attributes on the model.

### PR DESCRIPTION
**Pull request by Litiano**

### CODE REVIEW

**Comment by Litiano** [comment]
solve #1173

**Comment by divine** [comment]
Hello!

Could you please update with the base branch or we can take a look?

Thank you for your contribution!

**Comment by Giacomo92** [comment]
Can you also add some tests, please? @Litiano

**Comment by Litiano** [comment]
Hello @Giacomo92 and @divine ,

It was so long ago that I made this request, I don't even know if it is still compatible.
Perhaps this function is already implemented.
Unfortunately I can't do any tests right now, I used this package for a long time and I'm focused on other projects.
If someone can do the tests it would be good, if not, we can close this request.
Thanks.

**Comment by divine** [comment]
Closing as you wish.

**Pull request closed without merging**
