### PR TITLE
[refactor] Replaced Coveralls with Codecov

### PR DESCRIPTION
**Pull request by rennokki**
I don't know why, but it seems like Coveralls is playing games, so i decided to switch it up with Codecov.

@jenssegers For this, a secret named `CODECOV_TOKEN` might be needed that can be obtained from here: https://codecov.io/gh

### CODE REVIEW

**Comment by Smolevich** [comment]
@rennokki register your fork in codecov.io and add `CODECOV_TOKEN` to secrets
All requests finished with 400 error code https://github.com/rennokki/laravel-mongodb/commit/46a1d6d956c5e254581b344aec87cc303af3b93c/checks?check_suite_id=414641074

**Comment by Smolevich** [comment]
Problem with coveralls here https://github.com/php-coveralls/php-coveralls/pull/275

**Comment by Smolevich** [comment]
I will suggest compare codecov.io and coveralls.io and revert step with coveralls

**Comment by Smolevich** [comment]
We can replace using library `php-coveralls/php-coveralls` on https://github.com/cedx/coveralls.php

**Comment by Smolevich** [comment]
I prepared https://github.com/jenssegers/laravel-mongodb/pull/1923

**Comment by jenssegers** [comment]
I've added the secret :thumbs_up:

**Comment by Smolevich** [comment]
@jenssegers , What about #1923 ?

**Comment by jenssegers** [comment]
We can still use #1923 if we were to revert to coveralls. I'm ok with trying out codecov. Mainly interested in what they will report through the github action.

**Comment by Smolevich** [comment]
Ok, i suggest add two report services and compare

**Pull request merged**
