### PR TITLE
Fix for This database driver does not support dropping all tables Exception and couple of support methods

### PR DESCRIPTION
**Pull request by thilanga**
- addHasWhere
- dropIfExists
- dropAllTables
- getAllTables

dropAllTables and getAllTables are there to fix `This database driver does not support dropping all tables`

### CODE REVIEW

**Comment by thilanga** [comment]
StyleCI issue has been fixed

**Comment by jenssegers** [comment]
Is it possible to make a PR without the docblock changes? This makes it more difficult to review.

**Comment by thilanga** [comment]
Will do it tomorrow 👍

**Comment by jackmiras** [comment]
@thilanga just for curiosity, why you are adding functions with table sufix? Mongo is a data base that is document and collections '"based". Wouldn't be more idiomaticly if you call the function dropAllTables as dropAllCollections and the function getAllTables as getAllCollections?

**Pull request closed without merging**
