### PR TITLE
Allow Laravel 7

### PR DESCRIPTION
**Pull request by filipac**
This was released just now.

### CODE REVIEW

**Comment by filipac** [comment]
Hmm guess we have a breaking change: 
```
PHP Fatal error:  Access level to Jenssegers\Mongodb\Relations\BelongsToMany::newPivotQuery() must be public (as in class Illuminate\Database\Eloquent\Relations\BelongsToMany) in /home/runner/work/laravel-mongodb/laravel-mongodb/src/Jenssegers/Mongodb/Relations/BelongsToMany.php on line 268
```

**Comment by Smolevich** [comment]
@filipac, we plan to support new version not immediately, we want to show on new features and bugs, so supporting new version will be soon in version 4 of this library

**Comment by Smolevich** [comment]
@divine already works on this task

**Comment by filipac** [comment]
@Smolevich got it :) I created the branch to check if it works locally with L7 and it did :)

**Pull request closed without merging**
