### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Smolevich**
Add badge url as 
`https://github.com/<OWNER>/<REPOSITORY>/workflows/<WORKFLOW_NAME>/badge.svg?branch=master`

### CODE REVIEW

**Comment by jenssegers** [comment]
What makes this better than the shield.io one?

**Comment by Smolevich** [comment]
If shields.io more reliable, i can cancel PR

**Comment by Smolevich** [comment]
@jenssegers for comparing:
Host github.com:
https://github.com/jenssegers/laravel-mongodb/workflows/CI/badge.svg?branch=master
Host img.shields.io:
https://img.shields.io/github/workflow/status/jenssegers/laravel-mongodb/CI?branch=master

**Comment by jenssegers** [comment]
All other shields are from shield.io as well. The one from github would feel out of place in my opinion.

**Comment by Smolevich** [comment]
> All other shields are from shield.io as well. The one from github would feel out of place in my opinion.

ok

**Pull request closed without merging**
