### PR TITLE
Add support for laravel 6

### PR DESCRIPTION
**Pull request by djnet00**

### CODE REVIEW

**Comment by Smolevich** [comment]
@djnet00, join into slack channel. Link [here](https://github.com/jenssegers/laravel-mongodb/issues/1791)

**Comment by jenssegers** [comment]
I think we also need to increase the version of `testbench`

**Comment by jenssegers** [comment]
`- Installing laravel/framework (v5.8.35): Downloading (100%)` was installed on travis. So tests did not run on 6.

**Comment by simonschaufi** [comment]
@djnet00 In order to accomplish this, the composer.json needs to be adjusted right before the tests in travis config file

**Comment by jenssegers** [comment]
Supported added in 3.6.0

**Pull request closed without merging**
