### PR TITLE
Fix setup instruction

### PR DESCRIPTION
**Pull request by ericphamhoang**
Setup instruction should be 

'database' => env('DB_DATABASE') 

not 'database' => 'admin'

### CODE REVIEW

**Comment by Smolevich** [comment]
Mongodb has differents databases for authentication and using as source database
See [docs](https://docs.mongodb.com/manual/reference/connection-string/#authentication-options)

**Comment by Giacomo92** [comment]
Maybe the best choice is:
`DB_AUTH` @Smolevich

**Comment by divine** [comment]
This needs to be closed but merged in #1917

**Comment by Smolevich** [comment]
Duplicate, main functionality realized in https://github.com/jenssegers/laravel-mongodb/pull/1917

**Pull request closed without merging**
